name=Boardoza E22_900M22S LoRa Module
version=1.0.0
author=Boardoza <eray.eroglu@boardoza.com>
maintainer=Boardoza <Boardoza.com>
sentence=Library for Boardoza E22_900M22S LoRa Module
paragraph=This library provides an easy-to-use API for interfacing with the E22_900M22S LoRa module. It supports configuration, sending and receiving data, and advanced features such as power management and error handling. Designed for Arduino and PlatformIO projects, it includes clear example sketches and minimal dependencies, making it simple to integrate reliable long-range wireless communication into your applications.
category=Communication
url=https://github.com/Boardoza/Boardoza_E22_900M22S_LoRa_Module
architectures=*